students/K32422/Malaev_Stepan/LR_2_4/application/__init__.py
from flask import Flask
from .main.views import main_blueprint
from .tables.views import tables_blueprint


def create_app():
	app = Flask(__name__)
	app.register_blueprint(main_blueprint)
	app.register_blueprint(tables_blueprint)
	
	return app

students/K32422/Malaev_Stepan/LR_2_4/application/main/views.py
from flask import Blueprint, render_template
import application.db_functions as dbf

main_blueprint = Blueprint('main', __name__, template_folder='templates')


@main_blueprint.route('/')
def index():
	return render_template('index.jinja2', tables_info=dbf.GENERAL_INFO)

students/K32422/Malaev_Stepan/LR_2_4/application/tables/views.py
from flask import Blueprint, render_template, abort, request, jsonify
import application.db_functions as dbf
import logging

tables_blueprint = Blueprint('tables', __name__, template_folder='templates')


def validate_json_keys(request_json, required_keys):
	if not request_json:
		abort(400, description="Invalid or Missing JSON in request")
	
	if not all(key in request_json for key in required_keys):
		abort(400, description="Missing required key(s) in JSON")


@tables_blueprint.errorhandler(Exception)
def handle_error(e):
	logging.error(f"Error: {e}")
	return jsonify(message=f"An error occurred: {e}"), 500


@tables_blueprint.route('/tables/<name>')
def create(name: str):
	cols, rows = dbf.get_table_data(name)
	return render_template('datatable.jinja2', cols=cols, rows=rows, table_name=name, tables_info=dbf.GENERAL_INFO)


@tables_blueprint.route('/tables/operation/add', methods=['POST'])
def add_entry_to_table():
	request_json = request.json
	validate_json_keys(request_json, ["table_name", "table_data"])
	
	dbf.insert_entry(request_json["table_name"], request_json["table_data"])
	return jsonify(message='Entry was added!'), 200


@tables_blueprint.route('/tables/operation/get', methods=['POST'])
def get_table_entry():
	request_json = request.json
	validate_json_keys(request_json, ["table_name", "entry_id"])
	
	data = dbf.get_entry(request_json["table_name"], request_json["entry_id"])
	return jsonify(data), 200


@tables_blueprint.route('/tables/operation/update', methods=['POST'])
def update_entry_on_table():
	request_json = request.json
	validate_json_keys(request_json, ["table_name", "table_data"])
	
	dbf.update_entry(request_json["table_name"], request_json["table_data"])
	return jsonify(message='Entry was updated!'), 200


@tables_blueprint.route('/tables/operation/delete', methods=['POST'])
def delete_entry_on_table():
	request_json = request.json
	validate_json_keys(request_json, ["table_name", "entry_id"])
	
	dbf.delete_entry(request_json["table_name"], request_json["entry_id"])
	return jsonify(message='Entry was deleted!'), 200

students/K32422/Malaev_Stepan/LR_2_4/application/templates/datatable.jinja2
{% extends "index.jinja2" %}

{% block extra_css %}
    <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap-datatables.css') }}" rel="stylesheet">
{% endblock %}

{% block modal %}
    {% with modal_id="add", modal_title="Add new entry", form_id="addForm", error_id="addError", input_id_prefix="" %}
        {% include 'datatable_modal.jinja2' %}
    {% endwith %}

    {% with modal_id="update", modal_title="Update existing entry", form_id="updateForm", error_id="updateError", input_id_prefix="update" %}
        {% include 'datatable_modal.jinja2' %}
    {% endwith %}
{% endblock %}

{% block main %}
    <section id="table-section" class="section" data-table-name="{{ table_name }}">
        <!-- Card container -->
        <div class="card">
            <div class="card-body">
                <div id="spinner" class="d-flex justify-content-center">
                    <div class="spinner-grow text-primary" role="status">
                        <span class="sr-only"></span>
                    </div>
                </div>
                <div id="datatable-content" class="d-none">
                    {% include 'datatable_content.jinja2' %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block extra_js %}
    <script src="{{ url_for('static', filename='js/datatable.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/jquery/jquery.dataTables.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.datatables.js') }}"></script>
{% endblock %}

students/K32422/Malaev_Stepan/LR_2_4/application/templates/datatable_content.jinja2
{% macro button(class, label, modal_id, entry_id='') %}
    <button type="button" class="{{ class }}" data-bs-toggle="modal"
            data-bs-target="#{{ modal_id }}" data-entry-id="{{ entry_id }}"
            aria-label="{{ label }}">{{ label }}</button>
{% endmacro %}


{% macro table_row(row) %}
    <tr>
        {% for value in row %}
            <td>{{ value }}</td>
        {% endfor %}
        <td>
            {{ button('btn btn-primary btn-sm updateBtn', 'Update', 'update', row[0]) }}
            {{ button('btn btn-danger btn-sm deleteBtn', 'Delete', '', row[0]) }}
        </td>
    </tr>
{% endmacro %}


{% macro table_header(cols) %}
    <tr>
        {% for col in cols %}
            <th scope="col">{{ col }}</th>
        {% endfor %}
        <th scope="col">Operations</th>
    </tr>
{% endmacro %}

{% macro no_data(cols) %}
    <tr>
        <td colspan="{{ cols|length + 2 }}">No data available</td>
    </tr>
{% endmacro %}




{{ button('btn btn-primary btn-lg my-2', 'Add new entry', 'add') }}
<!-- Data table -->
<table class="table table-striped table-bordered" id="data-table">
    <thead>
    {{ table_header(cols) }}
    </thead>
    <tbody>
    <!-- Table data -->
    {% if rows|length > 0 %}
        {% for row in rows %}
            {{ table_row(row) }}
        {% endfor %}
    {% else %}
        {{ no_data(cols) }}
    {% endif %}

    </tbody>
</table>

students/K32422/Malaev_Stepan/LR_2_4/application/templates/datatable_modal.jinja2
{% macro form_field(col, prefix='', att='required') %}
    <div class="form-floating mb-3">
        <input type="text" name="{{ col }}" class="form-control"
               id="{{ prefix }}FloatingInput{{ col }}"
               placeholder="{{ col }}" {{ att }}>
        <label for="{{ prefix }}FloatingInput{{ col }}"
               id="{{ prefix }}FloatingInputLabel{{ col }}">{{ col }}</label>
    </div>
{% endmacro %}


<div class="modal fade" id="{{ modal_id }}" tabindex="-1" aria-labelledby="{{ modal_id }}Label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="{{ modal_id }}Label">{{ modal_title }}</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form id="{{ form_id }}">
                <div class="modal-body">
                    <div id="{{ error_id }}" class="alert alert-warning d-none" aria-live="polite"></div>

                    {% if modal_id == "update" %}
                        {{ form_field(cols[0], 'update', 'readonly') }}
                    {% endif %}

                    {% for col in cols[1:] %}
                        {{ form_field(col, input_id_prefix) }}
                    {% endfor %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Apply</button>
                </div>
            </form>
        </div>
    </div>
</div>

students/K32422/Malaev_Stepan/LR_2_4/application/templates/footer.jinja2
<footer id="footer" class="footer" role="contentinfo">

    <section class="copyright">
        &copy; <span id="year"></span> Copyright <strong><span>Database CRUD</span></strong>. All Rights Reserved
    </section>

    <section class="credits">
        Designed by <a href="https://t.me/Hate1Killa" target="_blank" rel="noopener noreferrer">Malaev Stepan</a>
    </section>

</footer>

students/K32422/Malaev_Stepan/LR_2_4/application/templates/header.jinja2
<header id="header" class="header fixed-top d-flex align-items-center" role="banner">
    <div class="d-flex align-items-center justify-content-between">

        <div class="logo-container">
            <a href="{{ url_for('main.index') }}" class="logo d-flex align-items-center">
                <span class="d-none d-lg-block">Database CRUD</span>
            </a>
        </div>

        <div class="sidebar-toggle-container">
            <i class="bi bi-list toggle-sidebar-btn" aria-hidden="true"></i>
        </div>

    </div>
</header>

students/K32422/Malaev_Stepan/LR_2_4/application/templates/index.jinja2
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    {% block title %}
        <title>Database CRUD</title>
    {% endblock %}

    <!-- Favicons -->
    <link href="{{ url_for('static', filename='image/logo.png' ) }}" rel="icon">

    <!-- Common CSS, JS, and other header elements -->
    <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='vendor/bootstrap-icons/bootstrap-icons.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">

    {% block extra_css %}
    {% endblock %}
</head>

<body>
{% block modal %}
{% endblock %}

{% include 'header.jinja2' %}
{% include 'sidebar.jinja2' %}

<main id="main" class="main" role="main">
    {% block main %}{% endblock %}
</main>

{% include 'footer.jinja2' %}

<a href="#" class="back-to-top d-flex align-items-center justify-content-center" aria-label="Back to top"><i
        class="bi bi-arrow-up-short" aria-hidden="true"></i></a>

<!-- Common JS files -->
<script src="{{ url_for('static', filename='vendor/jquery/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/script.js') }}"></script>

{% block extra_js %}
{% endblock %}

</body>
</html>

students/K32422/Malaev_Stepan/LR_2_4/application/templates/sidebar.jinja2
<aside id="sidebar" class="sidebar" role="navigation">
    <ul class="sidebar-nav" id="sidebar-nav">

        {% with url=url_for('main.index'), icon='bi bi-grid', name='General' %}
            {% include 'sidebar_item.jinja2' %}
        {% endwith %}

        {% with target='tables-nav', icon='bi bi-table', name='Tables', content='sidebar_tables_content.jinja2' %}
            {% include 'sidebar_collapsed_item.jinja2' %}
        {% endwith %}

    </ul>
</aside>

students/K32422/Malaev_Stepan/LR_2_4/application/templates/sidebar_collapsed_item.jinja2
<li class="nav-item">
    <a class="nav-link collapsed" data-bs-target="#{{ target }}" data-bs-toggle="collapse" href="#">
        <i class="{{ icon }}" aria-hidden="true"></i><span>{{ name }}</span>
        <i class="bi bi-chevron-down ms-auto" aria-hidden="true"></i>
    </a>
    <ul id="{{ target }}" class="nav-content collapse " data-bs-parent="#sidebar-nav">
        {% include content %}
    </ul>
</li><!-- End Tables Nav -->

students/K32422/Malaev_Stepan/LR_2_4/application/templates/sidebar_item.jinja2
<li class="nav-item">
    <a class="nav-link" href="{{ url }}">
        <i class="{{ icon }}" aria-hidden="true"></i>
        <span>{{ name }}</span>
    </a>
</li>

students/K32422/Malaev_Stepan/LR_2_4/application/templates/sidebar_sub_item.jinja2
<li>
    <a href="{{ url }}">
        <i class="bi bi-circle" aria-hidden="true"></i><span>{{ name }}</span>
    </a>
</li>

students/K32422/Malaev_Stepan/LR_2_4/application/templates/sidebar_tables_content.jinja2
{% for name in tables_info.keys() %}
    {% with url=url_for('tables.create', name=name), name=name %}
        {% include 'sidebar_sub_item.jinja2' %}
    {% endwith %}
{% endfor %}